#服务配置
server:
  port: 80
  max-http-header-size: 10240

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    date-format: com.bootdo.config.converter.JsonDateFormat
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 30d
      chain:
        enabled: true  # 启用资源链
        strategy:
          content:
            enabled: true  # 启用内容版本策略
            paths: /js/**,/css/**  # 指定应用版本控制的路径

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml, classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
    enable-sql-runner: true
  configuration-properties:
    prefix:
    #如果数据库为postgresql，则需要配置为blobType: BINARY
    blobType: BLOB
    #如果数据库为oracle或mssql，则需要配置为boolValue: 1
    boolValue: true

swagger:
  title: BootDrp
  description: BootDrp 是一个基于 Spring Boot 的快速开发平台
  version: 1.5.0
  email: bootdrp@vip.qq.com
  license: MIT

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: false # 需要关闭增强，具体原因见：https://github.com/xiaoymin/knife4j/issues/874
  setting:
    language: zh_cn